---
abstract: 'Write test tools that use new Test::Builder deatures'
author:
  - 'Chad Granum <exodist7@gmail.com>'
build_requires: {}
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Builder-Compat
provides:
  Test::Builder::Compat:
    file: lib/Test/Builder/Compat.pm
    version: '0.001001'
requires:
  Test::Simple: '0.88'
resources:
  bugtracker: http://github.com/Test-More/Test-Builder-Compat/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/Test-More/Test-Builder-Compat
version: '0.001001'
